"""
Base classes for trading agents and signals
"""
from enum import Enum
from dataclasses import dataclass
from typing import Optional, Dict, Any
from datetime import datetime


class Action(Enum):
    """Trading action types"""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """Trading signal generated by an agent"""
    symbol: str
    action: Action
    size: int
    strike: Optional[float] = None
    option_type: Optional[str] = None  # 'call' or 'put'
    strategy: str = ""
    confidence: float = 0.0
    timestamp: datetime = None
    metadata: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.metadata is None:
            self.metadata = {}


@dataclass
class Bar:
    """OHLC bar data"""
    open: float
    high: float
    low: float
    close: float
    volume: int = 0
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()


class BaseAgent:
    """Base class for all trading agents"""
    
    def __init__(self, name: str):
        self.name = name
        self.position_size = 0
        self.entry_premium = 0.0
        self.avg_premium = 0.0
        self.direction = None
        self.strike = None
        self.pt_level = 0.0
        self.sl_level = 0.0
        self.has_avg_down = False
        
    def on_bar(self, symbol: str, bar: Bar) -> Optional[Signal]:
        """
        Called on each new bar. Override in subclasses.
        
        Args:
            symbol: Trading symbol (e.g., 'SPY', 'QQQ')
            bar: OHLC bar data
            
        Returns:
            Signal object if action needed, None otherwise
        """
        raise NotImplementedError("Subclasses must implement on_bar")
    
    def reset(self):
        """Reset agent state"""
        self.position_size = 0
        self.entry_premium = 0.0
        self.avg_premium = 0.0
        self.direction = None
        self.strike = None
        self.pt_level = 0.0
        self.sl_level = 0.0
        self.has_avg_down = False

